### ISSUE TITLE
Doesnt work on 64 bit Notepad++

### ISSUE THREAD

**Issue by matcool** [jangko/nppnim#3]
I also tried compiling it for 64 bit but got these errors:

> C:\Users\user\Downloads\nppnim-master>nim c -d:release --cpu:i386 --passL:-m
32 --passC:-m32 nppnim
Hint: used config file 'C:\Users\user\AppData\Local\Programs\Nim\config\nim.
cfg' [Conf]
Hint: used config file 'C:\Users\user\Downloads\nppnim-master\nppnim.nim.cfg
' [Conf]
Hint: system [Processing]
Hint: nppnim [Processing]
Hint: winapi [Processing]
Hint: scintilla [Processing]
scintilla.nim(1360, 15) Error: type mismatch: got <SciHandle, int literal(2266),
 int, int>
but expected one of:
proc scisend(sci: SciHandle; iMessage: int; wParam = 0; lParam: sptr_t = 0): spt
r_t
  first type mismatch at position: 4
  required type: sptr_t
  but expression 'ord(onlyWordCharacters)' is of type: int
 expression: scisend(sci, 2266, pos, ord(onlyWordCharacters))

**Comment by jangko** [comment]
because `nim c -d:release --cpu:i386 --passL:-m32 --passC:-m32 nppnim` will produce 32 bit code using 64 bit compiler

use `nim c -d:release nppnim` on 64bit compiler to produce 64bit code

**Comment by matcool** [comment]
```
C:\Users\user\Downloads\nppnim-master>nim c -d:release nppnim
Hint: used config file 'C:\Users\user\AppData\Local\Programs\Nim\config\nim.cfg' [Conf]
Hint: used config file 'C:\Users\user\Downloads\nppnim-master\nppnim.nim.cfg' [Conf]
Hint: system [Processing]
Hint: nppnim [Processing]
Hint: winapi [Processing]
Hint: scintilla [Processing]
scintilla.nim(1157, 10) Error: type mismatch: got <int64> but expected 'int'
```

**Comment by jangko** [comment]
64 bit build issues are fixed, or you can download binary from [here](https://github.com/jangko/nppnim/releases/tag/v1.2.1)
